[package]
name = "nrap-analysis"
version = "0.1.0"
authors = ["emiliogonzalez"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.4"
thiserror = "1.0.10"
pretty_assertions = "0.6.1"
